language: c

compiler:
        - gcc
        #- clang

env:
        global:
                - secure: "i6k8tUrMbZO1bjHojJgwpnIMk9HyrFfpG8StlktUvkWPmmSIt7BxtW4cXLAQQh0NhTCxBRLE/teXXs19Wa/YP8VIjWSTI6B7U1WfZAmdjM2IVLwZqkj8TyYITiGrcjJCMe2sVqADyU10jwUwaMENiRhmFbbhYQQY10tpjkb3Sec="
        matrix:
                #- CFLAGS=--coverage CONFOPT=
                - CFLAGS=--coverage CONFOPT=--enable-multithread

#before_install:
#        - sudo apt-get update -qq
#        - sudo apt-get install -qq lcov rubygems
#        - gem install lcoveralls

before_script:
        - ./configure $CONFOPT && make

script:
        - make pytest
        - make atest
        - ./sample/crnl
        - make -C sample test

#after_success:
#        - lcov -c -d .libs -o coverage.info
#        - lcoveralls --retry-count 5 coverage.info

addons:
        coverity_scan:
                project:
                        name: "k-takata/Onigmo"
                        description: "Build submitted via Travis CI"
                notification_email: kentkt@csc.jp
                build_command_prepend: "./configure; make clean"
                build_command: "make -j 4"
                branch_pattern: coverity_scan
