language: c

branches:
        except:
                - onig-5.9.x-mod_for_bregonig-v2

compiler:
        - gcc
        - clang

env:
        - CFLAGS=--coverage CONFOPT=

sudo: false

addons:
        apt:
                packages:
                        - lcov

before_install:
        - gem install lcoveralls

before_script:
        - ./configure $CONFOPT && make && make testc testp testcu

script:
        - ./testc
        - ./testp
        - ./testcu
        - make -C sample test

after_success:
        - lcov -c -d .libs -o coverage.info
        - lcoveralls --retry-count 5 coverage.info
